[package]
name = "wut"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
default = ["panic_handler", "macros"]
ffi = []
mmio = []
panic_handler = []
macros = ["dep:wut-macros"]

[lib]
name = "wut"
crate-type = ["lib"]

[build-dependencies]
bindgen = "0.70.1"

[profile]
dev.panic = "abort"
release.panic = "abort"

[dependencies]
wut-macros = { path = "../wut-macros", optional = true }
flagset = { version = "0.4.6", default-features = false }
thiserror = { version = "2.0.3", default-features = false }
