[package]
name = "wut"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
default = ["default_alloc_handler", "default_panic_handler"]
ffi = []
mmio = []
default_alloc_handler = []
default_panic_handler = []

[lib]
name = "wut"
crate-type = ["lib"]

[build-dependencies]
bindgen = "0.70.1"

[profile]
dev.panic = "abort"
release.panic = "abort"

[dependencies]
flagset = { version = "0.4.6", default-features = false }
