[package]
name = "wut"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "wut"

[features]
default = []
panic_handler = []
collections = ["dep:hashbrown"]

[lib]
name = "wut"
crate-type = ["lib"]

[build-dependencies]
bindgen = "0.70.1"

[profile]
dev.panic = "abort"
release.panic = "abort"

[dependencies]
wut-macros = { path = "./macros" }
math = { path = "./math", version = "*" }
flagset = { version = "0.4.6", default-features = false }
thiserror = { version = "2.0.3", default-features = false }
hashbrown = { version = "0.15.2", optional = true }
