[package]
name = "sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "wut"

[profile]
dev.panic = "abort"
release.panic = "abort"

[build-dependencies]
bindgen = "0.71.1"

[features]
panic_handler = []
