[package]
name = "wut-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
name = "wut_macros"

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = { version = "2.0.95", features = ["full", "derive"] }
